### ISSUE TITLE
Remove branch 'master'

### ISSUE THREAD

**Issue by Powersource** [Code-at-LTH/projabo#1]
It doesn't really serve a purpose since gh-pages will act as our main and stable branch. You'd do this by going into the project settings (which I can't btw) and setting the default branch to gh-pages, then Code->Branches->remove master

**Comment by ErikBjare** [comment]
Never remove the master branch.

Don't make gh-pages serve as main and stable. Instead have it serve as a "latest stable release" and master as a "dev"/unstable branch which feature branches are merged into.

**Comment by velixo** [comment]
Agree with Bjare,  we need an unstable Dev branch and a stable release branch, as all SW projects with an intended user do.

Gh-pages will be very well suited for this, as we are making a browser game.
